apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bamaas/k8s-homelab-apps
    targetRevision: main
    path: config/node-red
    helm:
      valueFiles:
        - ../../config/node-red/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - Prune=true
  destination:
    server: https://kubernetes.default.svc
    namespace: home-automation
