apiVersion: v2
name: node-red
description: node-red
type: application
version: 0.1.0

dependencies:
  - name: node-red
    version: 0.29.0
    repository: https://schwarzit.github.io/node-red-chart/

  - name: mosquitto
    version: 13.3.0
    repository: https://charts.truecharts.org
